import {StyleSheet} from 'react-native';

const Styles = StyleSheet.create({
  headerIconContainer: {
    flexDirection: 'row',
    marginTop: 16,
    marginHorizontal: 16,
    justifyContent: 'space-between',
  },
  headerIconView: {
    height: 34,
    width: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  usersImageView: {
    height: 100,
    width: 100,
    borderRadius: 50,
    backgroundColor: '#FFF2C6',
    position: 'absolute',
    bottom: -50,
    left: 16,
  },
  usersNameView: {
    fontFamily: 'Mulish',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 30,
    letterSpacing: -0.40799999237060547,
    textAlign: 'left',
    color: '#222222',
    marginTop: 56,
  },
  usersDetailsTitle: {
    fontFamily: 'Mulish',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'left',
    color: '#7A7A7A',
  },
  usersDetailsInput: {
    paddingLeft: 20,
    height: 40,
    borderRadius: 4,
    marginTop: 8,
    backgroundColor: '#e3e8e8',
  },
  usersDetailsInputView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e3e8e8',
    height: 40,
    borderRadius: 4,
    marginTop: 8,
    paddingRight: 5,
  },
  usersDetailsEditIcon: {
    margin: 5,
    height: 20,
    width: 20,
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  usersDetailsSaveBtn: {
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 21,
    textAlign: 'left',
    color: '#9EA0A0',
    marginRight: 10,
  },
  usersDocumentsDescription: {
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 18,
    textAlign: 'center',
    color: '#222222',
    marginTop: 8,
    width: 193,
  },
  footerView: {
    position: 'absolute',
    bottom: 40,
    marginRight: 8,
    width: '100%',
  },
  footerBtn: {
    borderRadius: 8,
    backgroundColor: '#FED250',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginTop: 16,
  },
  footerBtnText: {
    fontFamily: 'Mulish',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20.08,
    textAlign: 'left',
    color: '#222222',
  },
});
export default Styles;
