import {StyleSheet} from 'react-native';

const Styles = StyleSheet.create({
  mainContainerIdVerification: {
    marginTop: 72,
    marginHorizontal: 16,
    flex: 1,
  },
  idVerifyText: {
    fontFamily: 'Mulish',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 27,
    textAlign: 'left',
    color: '#222222',
  },
  idVerifyDescription: {
    fontFamily: 'Mulish',
    marginTop: 8,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 21,
    textAlign: 'justify',
    color: '#7A7A7A',
  },
  selectedCountriesTitleText: {
    fontFamily: 'Mulish',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: -0.40799999237060547,
    textAlign: 'left',
    color: '#222222',
  },
  selectedCountryOuterCheckbox: {
    height: 24,
    width: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FED250',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedCountryInnerCheckbox: {
    height: 12,
    width: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FED250',
    backgroundColor: '#FED250',
  },
  selectedCountriesText: {
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 22,
    letterSpacing: -0.40799999237060547,
    textAlign: 'left',
    color: '#222222',
    marginLeft: 10,
  },
  unSelectedCountryOuterCheckbox: {
    height: 24,
    width: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#7A7A7A',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F7F7F7',
  },
  unSelectedCountryInnerCheckbox: {
    height: 12,
    width: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#F7F7F7',
    backgroundColor: '#F7F7F7',
  },
  unSelectedCountriesText: {
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 22,
    letterSpacing: -0.40799999237060547,
    textAlign: 'left',
    color: '#7A7A7A',
    marginLeft: 10,
  },
  idProofsMainContainerView: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    marginTop: 24,
  },
  idProofsIcons: {
    height: 40,
    width: 40,
    borderColor: '#DDDDDD',
    borderWidth: 1,
  },
  idProofsTitle: {
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 21,
    textAlign: 'left',
    color: '#000000',
  },
  idProofsDescription: {
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 21,
    textAlign: 'left',
    color: '#9EA0A0',
  },
  idProofView: {marginTop: 24, marginLeft: 24, flexDirection: 'row'},
  drivingLicenceView: {
    marginTop: 32,
    marginLeft: 24,
    marginBottom: 24,
    flexDirection: 'row',
  },
  timeTakenUnhighlightText: {
    marginTop: 12,
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
    textAlign: 'left',
    color: '#7A7A7A',
  },
  timeTakenHighlightText: {
    fontFamily: 'Mulish',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 24,
    textAlign: 'left',
    color: '#222222',
  },
  footerContainer: {position: 'absolute', bottom: 40, marginHorizontal: 8},
  footerView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerIcon: {
    height: 24,
    width: 24,
    borderWidth: 1,
    borderColor: '#222222',
  },
  privacyPolicyUnhighlightText: {
    marginLeft: 12,
    fontFamily: 'Mulish',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 21,
    textAlign: 'justify',
    color: '#595B5B',
  },
  privacyPolicyHighlightText: {
    fontFamily: 'Mulish',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 21,
    textAlign: 'justify',
    color: '#44B1D5',
  },
  footerButtonView: {
    borderRadius: 8,
    backgroundColor: '#FED250',
    marginTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  footerButtonText: {
    fontFamily: 'Mulish',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20.08,
    textAlign: 'left',
    color: '#222222',
  },
});
export default Styles;
